[theme]
primaryColor="#7B337E"          # Dodger Blue (sliders, buttons)
backgroundColor="#210635"       # Very light ash background
secondaryBackgroundColor="#7B337E"  # Sky blue panels
textColor="#949478"             # Black text