[theme]
primaryColor="#1E90FF"          # Dodger Blue (sliders, buttons)
backgroundColor="#CECCD0"       # Very light ash background
secondaryBackgroundColor="#87CEEB"  # Sky blue panels
textColor="#000000"             # Black text